package com.wg.springmall.entity;

public class AdminMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spring_mall_admin_menu.id
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spring_mall_admin_menu.title
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spring_mall_admin_menu.icon
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spring_mall_admin_menu.href
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spring_mall_admin_menu.spread
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    private Boolean spread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spring_mall_admin_menu.target
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spring_mall_admin_menu.parent_Code
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_spring_mall_admin_menu.menu_Code
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    private String menuCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spring_mall_admin_menu.id
     *
     * @return the value of tb_spring_mall_admin_menu.id
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spring_mall_admin_menu.id
     *
     * @param id the value for tb_spring_mall_admin_menu.id
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spring_mall_admin_menu.title
     *
     * @return the value of tb_spring_mall_admin_menu.title
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spring_mall_admin_menu.title
     *
     * @param title the value for tb_spring_mall_admin_menu.title
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spring_mall_admin_menu.icon
     *
     * @return the value of tb_spring_mall_admin_menu.icon
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spring_mall_admin_menu.icon
     *
     * @param icon the value for tb_spring_mall_admin_menu.icon
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spring_mall_admin_menu.href
     *
     * @return the value of tb_spring_mall_admin_menu.href
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spring_mall_admin_menu.href
     *
     * @param href the value for tb_spring_mall_admin_menu.href
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spring_mall_admin_menu.spread
     *
     * @return the value of tb_spring_mall_admin_menu.spread
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public Boolean getSpread() {
        return spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spring_mall_admin_menu.spread
     *
     * @param spread the value for tb_spring_mall_admin_menu.spread
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public void setSpread(Boolean spread) {
        this.spread = spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spring_mall_admin_menu.target
     *
     * @return the value of tb_spring_mall_admin_menu.target
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spring_mall_admin_menu.target
     *
     * @param target the value for tb_spring_mall_admin_menu.target
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spring_mall_admin_menu.parent_Code
     *
     * @return the value of tb_spring_mall_admin_menu.parent_Code
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spring_mall_admin_menu.parent_Code
     *
     * @param parentCode the value for tb_spring_mall_admin_menu.parent_Code
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spring_mall_admin_menu.menu_Code
     *
     * @return the value of tb_spring_mall_admin_menu.menu_Code
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spring_mall_admin_menu.menu_Code
     *
     * @param menuCode the value for tb_spring_mall_admin_menu.menu_Code
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }
}