package com.wg.springmall.dao;

import com.wg.springmall.entity.AdminMenu;

public interface AdminMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spring_mall_admin_menu
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spring_mall_admin_menu
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    int insert(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spring_mall_admin_menu
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    int insertSelective(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spring_mall_admin_menu
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    AdminMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spring_mall_admin_menu
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    int updateByPrimaryKeySelective(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spring_mall_admin_menu
     *
     * @mbg.generated Sat Oct 03 01:19:39 CST 2020
     */
    int updateByPrimaryKey(AdminMenu record);
}